- apps:
    - qBittorrent:
        icon: qbittorrent.png
        href: https://qbittorrent.pluto
        ping: https://qbittorrent.pluto
        widget:
            type: qbittorrent
            url: https://qbittorrent.pluto
    - Jellyfin:
        icon: jellyfin.png
        href: https://jellyfin.pluto
        ping: https://jellyfin.pluto
    - Sonarr:
        icon: sonarr.png
        href: https://sonarr.pluto
        ping: https://sonarr.pluto
    - Radarr:
        icon: radarr.png
        href: https://radarr.pluto
        ping: https://radarr.pluto
    - Prowlarr:
        icon: prowlarr.png
        href: https://prowlarr.pluto
        ping: https://prowlarr.pluto
    - Bazarr:
        icon: bazarr.png
        href: https://bazarr.pluto
        ping: https://bazarr.pluto
    - File Browser:
        icon: filebrowser.png
        href: https://filebrowser.pluto
        ping: https://filebrowser.pluto

- admin:
    - Portainer:
        icon: portainer.png
        href: https://portainer.pluto
        ping: https://portainer.pluto
        widget:
            type: portainer
            url: https://portainer.pluto
            env: 2
            key: $homepage-portainer-api-key
    - Pi-hole:
        icon: pi-hole.png
        href: https://pi.pluto/admin
        ping: https://pi.pluto/admin
    - Grafana:
        icon: grafana.png
        href: https://grafana.pluto
        ping: https://grafana.pluto
    - Home Assistant:
        icon: home-assistant.png
        href: https://homeassistant.pluto
        ping: https://homeassistant.pluto

