root /usr/share/nginx/www;
index index.html index.htm;

location / {
  proxy_pass http://homepage:3000/;
  proxy_set_header Host $http_host;
}

location /qbittorrent/ {
  proxy_pass http://qbittorrent:8090/;
  proxy_set_header Host $http_host;
}

location /filebrowser/ {
  proxy_pass http://filebrowser:80/;
  proxy_set_header Host $http_host;
}

location /portainer/ {
  proxy_pass http://portainer:9000/;
  proxy_set_header Host $http_host;
}

location /prowlarr {
    proxy_pass http://prowlarr:9696;
}

location ~ /prowlarr(/[0-9]+)?/api {
    proxy_pass http://prowlarr:9696;
}

location ^~ /sonarr {
    proxy_pass http://sonarr:8989;

}

location ^~ /sonarr/api {
    proxy_pass http://sonarr:8989;
}

location ^~ /radarr {
    proxy_pass http://radarr:7878;

}

location ^~ /radarr/api {
    proxy_pass http://radarr:7878;
}

location ^~ /bazarr {
    proxy_pass http://bazarr:6767;

}

location ^~ /bazarr/api {
    proxy_pass http://bazarr:6767;
}

